### ISSUE TITLE
Invalid "exports" main target "dist/index.cjs.js" 

### ISSUE THREAD

**Issue by kopax** [mesqueeb/merge-anything#10]
I am trying to build the documentation of [my project](https://github.com/bootstrap-styled/css-utils/issues/58) and I have the following error:

```bash
> @bootstrap-styled/css-utils@1.2.6 styleguide /home/dka/workspace/github.com/bootstrap-styled/css-utils
> styleguidist server

Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.cjs.js" defined in the package config /home/dka/workspace/github.com/bootstrap-styled/css-utils/node_modules/merge-anything/package.json
Error [ERR_INVALID_PACKAGE_TARGET]: Invalid "exports" main target "dist/index.cjs.js" defined in the package config /home/dka/workspace/github.com/bootstrap-styled/css-utils/node_modules/merge-anything/package.json
    at resolveExportsTarget (internal/modules/cjs/loader.js:542:13)
    at resolveExportsTarget (internal/modules/cjs/loader.js:581:20)
    at applyExports (internal/modules/cjs/loader.js:455:14)
    at resolveExports (internal/modules/cjs/loader.js:508:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:632:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/dka/workspace/github.com/bootstrap-styled/css-utils/node_modules/styled-components/dist/styled-components.cjs.js:17:29)
npm ERR! code ELIFECYCLE
```

Is this related to this project? Seems like export are wrong.

**Comment by mesqueeb** [comment]
I don’t know. It will depend how you are importing my package. Can you show me where and how you import my package?

**Comment by kopax** [comment]
I am not, it seems to be in here: `styled-components/dist/styled-components.cjs.js:17:29`, I am closing since I was able to fix it by upgrading all the dependencies. Thanks

**Comment by mesqueeb** [comment]
@kopax ok great! Let me know if you have any more problems with my library.
